name: Train and Deploy Model

on:
  push:
    branches: [main]

env:
  CSV_URL: "MLproject/asap2_preprocessing/train_preprocessed.csv"
  TARGET_VAR: "score_label"

jobs:
  train-and-deploy:
    name: Train and Deploy Model Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # ---------------------------------
      # 1. checkout repository
      # ---------------------------------
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: pull LFS files
        run: |
          git lfs pull
          git lfs track "*.pkl"

      # ---------------------------------
      # set up Python 3.12.7
      # ---------------------------------
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.7

      # ---------------------------------
      # 3. check env
      # ---------------------------------
      - name: Check Env
        run: |
          python --version
          pip list
          echo $CSV_URL

      # ---------------------------------
      # 4. install dependencies
      # ---------------------------------
      - name: Install Dependencies
        run: |
          pip -m pip install --upgrade pip
          pip install mlflow

      # ---------------------------------
      # 5. Run Mlflow Project
      # ---------------------------------
      - name: Run MLflow Project
        run: |
          mlflow run MLproject --env-manager=local

      # ---------------------------------
      # 6. get mlflow run id from mlflow output
      # ---------------------------------
      - name: Get Latest MLflow Run ID
        id: get_run_id
        run: |
          RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
          echo "run_id=$RUN_ID" >> $GITHUB_ENV
          echo "Latest MLflow Run ID: $RUN_ID"

      # ---------------------------------
      # 8. install python dependencies
      # ---------------------------------
      - name: Install Python Dependencies
        run: |
          pip install mlflow

      # ---------------------------------
      # 9. Upload to LFS
      # ---------------------------------
      - name: Upload Model to LFS
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          git add .
          git commit -m "Add model from run"
          git push origin main

      # ---------------------------------
      # 10. Build Docker Image
      # ---------------------------------
      - name: Build Docker Image
        run: |
          mlflow models build-docker -model-uri "runs:/$RUN_ID/model" -n essay-scoring-model

      # ---------------------------------
      # 11. login to Docker Hub
      # ---------------------------------
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      # ---------------------------------
      # 12. Tag Docker Image
      # ---------------------------------
      - name: Tag Docker Image
        run: |
          docker tag essay-scoring-model:latest ${{ secrets.DOCKER_USERNAME }}/essay-scoring-model:latest

      # ---------------------------------
      # 13. Push Docker Image to Docker Hub
      # ---------------------------------
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/essay-scoring-model:latest
